# Generated by Django 4.2.4 on 2023-08-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_service_profile_first_name_profile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
