# Generated by Django 4.2.4 on 2023-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_short_decription_service_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
