# Generated by Django 4.2.4 on 2023-08-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_content',
            new_name='description',
        ),
    ]
